### ISSUE TITLE
Mouse not showing

### ISSUE THREAD

**Issue by SintcoLTD** [alexlostorto/alexlostorto.github.io#1]
When visiting the website, i can not see my mouse

**Comment by alexlostorto** [comment]
What device are you using? Is it touchscreen?

**Comment by alexlostorto** [comment]
I'm going to change the code for the custom cursor soon.

Which page does the cursor not show? Main page, all pages?

**Comment by NajmAjmal** [comment]
Magic-notes, I believe that there is no image to replace my mouse, therefore I can not see it

**Comment by SintcoLTD** [comment]
all

**Comment by alexlostorto** [comment]
I changed the code for the custom cursor on the main page: [https://alexlostorto.github.io/](https://alexlostorto.github.io/).

Check if it works now. If your screen is wider than it is tall then it should appear.

**Comment by NajmAjmal** [comment]
Yes, I can see the custom mouse now. It looks very nice.

**Comment by alexlostorto** [comment]
I will add it to the rest of the pages then :)
