### ISSUE TITLE
Mouse position [SUGGESTION]

### ISSUE THREAD

**Issue by NajmAjmal-old** [alexlostorto/alexlostorto.github.io#2]
Hi,

When the website first loads, the custom mouse appears in the top-left corner of the window. 

Because your loading animations streak outward from the middle. I would suggest loading the mouse in the centre of the screen when the website is loaded.

Thanks Najm,

**Comment by alexlostorto** [comment]
Yeah, that's actually a good suggestion, but I think that the cursor appearing in the middle would ruin the look of the star animation.

If it's in the corner, it's less noticeable and therefore the viewer's attention is focused on the animation.

I think before I updated the custom cursor, it only loaded when a mouse movement was detected. However, after you pointed out that it didn't show up on your computer, I decided to automatically display the cursor on all landscape devices (laptops, tablets etc). 

![image](https://user-images.githubusercontent.com/114829362/236312494-7acce7d5-f203-4cf7-834e-385c8f622fdb.png)
![image](https://user-images.githubusercontent.com/114829362/236312537-ae1a09b8-b654-44a1-b2a9-4105bd66777f.png)
